const API = {
  HOME: "home",
  BLOG_HOME: "blog/home",
  BLOG_DETAILS: "blog/details",
  BLOG_SEARCH: "blog/search",
  SEARCH: "search",
  UNBOXING_CHANLLENG: "unboxing_challenge",
  PRODUCT_DETAILS: "product_details",
  FILTER: "filter",
  SMART_SHOPPING: "engagement/category",
  ADD_TO_CART: "add_to_cart",
  CREATE_CART: "create_cart",
  GET_CART: "get_cart",
  REMOVE_CART_ITEM: "remove_cart_item",
  CART_PRODUCT_IDS: "cart_product_ids",
  PRODUCTS: "products",
  CATEGORY: "category",
  SUB_CATEGORY: "sub_category",
  Wishlist: "wishlist",
  SETTING: "setting",
  REGISTER: "register",
  LOGIN: "login",
  LOGOUT: "logout",
  REMOVE_WISHLIST: "remove_wishlist",
  ADD_WISHLIST: "add_wishlist",
  ADD_SHIPPING_ADDRESS: "add_shipping_address",
  COUNTRY: "country",
  CITY: "city",
  AREA: "area",
  SHIPPING_ADDRESS: "shipping_address",
  DELETE_SHIPPING_ADDRESS: "delete_shipping_address",
  CHECKOUT: "checkout",
  PLACE_ORDER: "place_order",
  ORDERS: "orders",
  ORDER_DETAILS: "order_details",
  UPDATE_SHIPPING_ADDRESS: "update_shipping_address",
  PROFILE: "profile",
  UPDATE_PROFILE_PHOTO: "update-profile-photo",
  UPDATE_PROFILE: "update-profile",
  CHANGE_PASSWORD: "change_password",
  ALLLANGUAGES: "allLanguages",
  SOCIAL_LOGIN: "social_login",
  TRANSLATIONS: "translations",
  VALIDATEBARCODE: "validateBarcode",
  ACCOUNT_DELETE: "account_delete",
  GET_COUNTRY: "country",
  Merge_Cart: "merge_cart",
  GETRECOMMENDEDPRODUCTS: "getRecommendedProducts",
  FORGOTPASSWORD: "forgot",
  SendOtp: "send_otp",
  OTP_VERIFY: "otp_verify",
  MOBILE_VERIFY: "mobile_verified",
  RESET_PASSWORD: "reset_password",
  VALIDATE_COUPON: "validate_coupon",
  NEW_PRODUCTS: "new_product",
  ADD_BLOG_COMMENT: "blog/add_comment",
  CONTACT_ENQUIRY: "contact_enquiry",
  SMART_SHOPPING_SUBCATEGORY: "engagement/sub_category",
  SMART_SHOPPING_DETAILS: "engagement/details",
  GET_BUNDLE_PRODUCTS_ITEM: "get_bundle_product_item",
  GET_BUNDLE_PRODUCTS: "get_bundle_products",
  GET_SIMILAR_PRODUCT: "similar_product",
  GRID_PRODUCTS: "grid_product",
  IS_REGISTERED_USER: "is_registerd_user",
  AUTOCOMPLETE: "autocomplete",
  GET_USER_BY_ID: "get_user_data",
  SHIPPING_ADDRESS_BY_ID: "details_shipping_address",

  // smart shopping endpoints
  GET_ENG_CATEGORY: "engagement/category",
  GET_ENG_SUB_CATEGORY: "engagement/sub_category",
  GET_ENG_PRODUCTS: "engagement/products",
  ENG_LIST: "engagement/list",
  ENG_DETAILS: "engagement/details",
  ENG_TAG_PRODUCTS: "engagement/tag_products",
  ENG_PRODUCTS_BY_TAG: "engagement/generate_photo",
  ENG_ADD_TO_CART: "add_to_cart_engagement",
  CHECK_SHIPPING_APPLICALE: "shipping_applicable_checkout",
  PLACE_ORDER_TEMP: "place_order_temp",
  NGENIUS: "ngenius/payment",
  PAYMENT_VALIDATE: "ngenius/success",
  TABBY: "tabby/payment",
  TAMARA: "tamara/payment",

  // rating endpoints
  ADD_RATING: "add_rating_review",
  GET_RATING_REVIEW_DETAIL: "get_rating_review_detail",
  UPDATE_RATING_REVIEW: "update_rating_review",
  DELETE_REVIEW_RATING_PHOTO: "delete_rating_review_photo",
  GET_REVIEW_LIST: "rating_review_list",
  LIKE_REVIEW: "like",

  // newsletter endpoints
  SUBSCRIBE_NEWSLETTER: "newsletter",
  STORE_LOACTION: "store_location",
  GET_GIFT_LIST: "gift/listing",
  GET_GIFT_MAKER: "gift-maker",
};

export default API;
